core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('live/', views.live_dashboard, name='live_dashboard'),
    path('profile/', views.profile_edit, name='profile_edit'),
]

helpdesk/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('ticket/add/', views.ticket_add, name='ticket_add'),
    path('ticket/create/', views.ticket_crete, name='ticket_create'),
    path('ticket/create/new/', views.ticket_crete_step02, name='ticket_create_step02'),
    path('ticket/create/new/done/', views.public_ticket_create, name='public_ticket_create'),
    path('ticket/<email>/<secret>/', views.ticket_detail, name='ticket_detail'),
    path('ticket/<pk>/', views.ticket_edit, name='ticket_edit'),
    path('tickets/', views.ticket_list_all, name='ticket_list_all'),
    path('tickets/todo/', views.ticket_list_todo, name='ticket_list_todo'),
    path('tickets/done/', views.ticket_list_done, name='ticket_list_done'),
    path('tickets/closed/', views.ticket_list_closed, name='ticket_list_closed'),
    path('tickets/resolved/', views.ticket_list_resolved, name='ticket_list_resolved'),
    path('tickets/processing/', views.ticket_list_processing, name='ticket_list_processing'),
    path('tickets/comment/<pk>/', views.ticket_comment, name='ticket_comment'),
    path('tickets/ajax/load-questions/', views.load_questions, name='load_questions'),
    path('tickets/ajax/feed/', views.ticket_feed, name='ticket_feed'),
    path('tickets/ajax/data/', views.json_dashboard_context, name='json_dashboard_context'),
    path('tickets/ajax/tables/', views.tickets_tables_builder, name='tickets_tables_builder'),
]

zdesk/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from zdesk import settings

admin.site.site_header = 'zDesk'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('helpdesk.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

helpdesk/models.py
import uuid

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils.text import slugify

from core.models import Active, TimeStampedModel


class Queue(Active, TimeStampedModel):
    """
    Uma fila é uma coleção de tickets para o que geralmente seriam áreas ou
    departamentos de negócios.
    Por exemplo, uma empresa pode ter uma fila para cada Produto fornecido,
    ou uma fila para cada uma das Contas, Pré-Vendas e Suporte.

    A queue is a collection of tickets into what would generally be business
    areas or departments.
    For example, a company may have a queue for each Product they provide, or
    a queue for each of Accounts, Pre-Sales, and Support.
    """

    title = models.CharField('Title', max_length=100)

    description = models.TextField('Description')

    slug = models.SlugField('Slug', max_length=50, unique=True, blank=True, null=True,
                            help_text='This slug is used when building ticket IDs.'
                                      'Once set, try not to change it or e-mailing may get messy.')

    image = models.ImageField(upload_to='queue/', blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)

        super(Queue, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name = 'Queue'
        verbose_name_plural = 'Queues'


class QueueQuestion(Active, TimeStampedModel):
    """
    Um item na base de conhecimento, problemas e perguntas frequentes.
    As perguntas vinculadas a uma Queue são usadas para gerar o fomulário de novo ticket.
    """
    queue = models.ForeignKey(Queue, on_delete=models.CASCADE, verbose_name='Queue')
    order = models.PositiveIntegerField('ordem', default=0)
    question = models.CharField('Question', max_length=256,
                                help_text='Pergunta para formulário de abertura de tickets')

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('queue', 'order')
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


def make_secret():
    return str(uuid.uuid4())


class Ticket(Active, TimeStampedModel):
    """
    Para permitir a entrada de um ticket o mais rápido possível, apenas o
    campos mínimos simples são obrigatórios. Isso basicamente nos permite
    classifique e gerencie o ticket. O usuário sempre pode voltar e
    insira mais informações posteriormente.

    Um bom exemplo disso é quando um cliente está ao telefone e
    você deseja fornecer a eles um ID do ticket o mais rápido possível. Você pode
    insira algumas informações básicas, salve o ticket, forneça o ID ao cliente
    desligue o telefone e adicione mais detalhes posteriormente
    (quando o cliente não estiver na linha).

    Observe que assign_to é opcional - tickets não atribuídos são exibidos em
    o painel para solicitar aos usuários que se apropriem deles.

    To allow a ticket to be entered as quickly as possible, only the
    bare minimum fields are required. These basically allow us to
    sort and manage the ticket. The user can always go back and
    enter more information later.

    A good example of this is when a customer is on the phone, and
    you want to give them a ticket ID as quickly as possible. You can
    enter some basic info, save the ticket, give the customer the ID
    and get off the phone, then add in further detail at a later time
    (once the customer is not on the line).

    Note that assigned_to is optional - unassigned tickets are displayed on
    the dashboard to prompt users to take ownership of them.
    """
    OPEN_STATUS = 1
    REOPENED_STATUS = 2
    RESOLVED_STATUS = 3
    CLOSED_STATUS = 4
    DUPLICATE_STATUS = 5
    PROCESSING_STATUS = 6

    STATUS_CHOICES = (
        (OPEN_STATUS, 'Open'),
        (PROCESSING_STATUS, 'Em Andamento'),
        (REOPENED_STATUS, 'Reopened'),
        (RESOLVED_STATUS, 'Resolved'),
        (CLOSED_STATUS, 'Closed'),
        (DUPLICATE_STATUS, 'Duplicate'),
    )

    PRIORITY_CHOICES = (
        (1, '1. Critical'),
        (2, '2. High'),
        (3, '3. Normal'),
        (4, '4. Low'),
        (5, '5. Very Low'),
    )

    queue = models.ForeignKey(Queue, on_delete=models.CASCADE, verbose_name='Queue')

    problems = ArrayField(models.CharField(max_length=200), blank=True)

    submitter_name = models.CharField('Contact name', max_length=50, blank=True, null=True)

    submitter_company = models.CharField('Company', max_length=50, blank=True, null=True)

    submitter_phone = models.CharField('Phone number', max_length=16, blank=True, null=True)

    submitter_email = models.EmailField('Submitter E-Mail', blank=True, null=True,
                                        help_text='The submitter will receive an email for all public '
                                                  'follow-ups left for this task.')

    status = models.IntegerField('Status', choices=STATUS_CHOICES, default=OPEN_STATUS)

    priority = models.IntegerField('Priority', choices=PRIORITY_CHOICES, default=3, blank=3,
                                   help_text='1 = Highest Priority, 5 = Low Priority')

    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='assigned_to',
                                    blank=True, null=True, verbose_name='Assigned to')

    tecnico_pre_diagnostico = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                                related_name='tecnico_pre_diagnostico', blank=True, null=True,
                                                verbose_name='Técnico pré diagnóstico')

    tecnico_de_campo = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                         related_name='tecnico_de_campo', blank=True, null=True,
                                         verbose_name='Técnico de campo')

    is_customer = models.BooleanField('É cliente', default=False)

    customer_code = models.CharField('Código do cliente', max_length=6, blank=True, null=True)

    order = models.CharField('Código do pedido', max_length=10, blank=True, null=True)

    losses = models.DecimalField('Prejuízo', max_digits=16, decimal_places=10, blank=True, default=0)

    need_paper = models.BooleanField('Tem papel', default=False)

    resolution_report = models.TextField('Relatório final', blank=True, null=True,
                                         help_text='The resolution provided to the customer by our staff.')

    secret_key = models.CharField("Secret key needed for viewing/editing ticket by non-logged in users",
                                  max_length=36,
                                  default=make_secret)


class TicketUpdate(Active, TimeStampedModel):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, verbose_name='Ticket')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='user', blank=True, null=True,
                             verbose_name='Usuário')
    title = models.CharField('Título', max_length=100, blank=True, null=True)
    comment = models.TextField('Comentário', blank=True, null=True)
    public = models.BooleanField('Público', blank=True, null=True, default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Update'
        verbose_name_plural = 'Updates'

helpdesk/forms.py
from django.forms import ModelForm, Select, CheckboxInput, Textarea, TextInput, EmailInput, CheckboxSelectMultiple, \
    NumberInput

from .models import Ticket


class TicketManageForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['status',
                  'priority',
                  'tecnico_pre_diagnostico',
                  'tecnico_de_campo',
                  'is_customer',
                  'customer_code',
                  'order',
                  'losses',
                  'need_paper',
                  'resolution_report', ]

        widgets = {
            'status': Select(attrs={'class': 'form-control', 'placeholder': 'Status'}),
            'priority': Select(attrs={'class': 'form-control', 'placeholder': 'Prioridade'}),
            'tecnico_pre_diagnostico': Select(attrs={'class': 'form-control', 'placeholder': 'Pré diagnostico'}),
            'tecnico_de_campo': Select(attrs={'class': 'form-control', 'placeholder': 'Tecnico de campo'}),
            'is_customer': CheckboxInput(attrs={'class': 'form-control'}),
            'customer_code': TextInput(attrs={'class': 'form-control'}),
            'order': TextInput(attrs={'class': 'form-control'}),
            'losses': NumberInput(attrs={'class': 'form-control'}),
            'need_paper': CheckboxInput(attrs={'class': 'form-control'}),
            'resolution_report': Textarea(attrs={'class': 'form-control'})
        }


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['queue',
                  'problems',
                  'submitter_name',
                  'submitter_company',
                  'submitter_phone',
                  'submitter_email',
                  'status',
                  'priority',
                  'tecnico_pre_diagnostico',
                  'tecnico_de_campo',
                  'is_customer',
                  'customer_code',
                  'order',
                  'need_paper',
                  'resolution_report', ]

        widgets = {
            'queue': Select(attrs={'class': 'form-control', 'placeholder': 'Queue'}),
            'problems': CheckboxSelectMultiple(attrs={'class': 'form-control'}),
            'submitter_name': TextInput(attrs={'class': 'form-control'}),
            'submitter_company': TextInput(attrs={'class': 'form-control'}),
            'submitter_phone': TextInput(attrs={'class': 'form-control'}),
            'submitter_email': EmailInput(attrs={'class': 'form-control'}),
            'status': Select(attrs={'class': 'form-control', 'placeholder': 'Status'}),
            'priority': Select(attrs={'class': 'form-control', 'placeholder': 'Prioridade'}),
            'tecnico_pre_diagnostico': Select(attrs={'class': 'form-control', 'placeholder': 'Pré diagnostico'}),
            'tecnico_de_campo': Select(attrs={'class': 'form-control', 'placeholder': 'Tecnico de campo'}),
            'is_customer': CheckboxInput(attrs={'class': 'form-control'}),
            'customer_code': TextInput(attrs={'class': 'form-control'}),
            'order': TextInput(attrs={'class': 'form-control'}),
            'need_paper': CheckboxInput(attrs={'class': 'form-control'}),
            'resolution_report': Textarea(attrs={'class': 'form-control'})
        }

templates/helpdesk/create_ticket_done.html
<!doctype html>
{% load static %}
<html class="no-js " lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Django simple ticketing system">

    <title>:: zDesk :: Ticket criado</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png"> <!-- Favicon-->
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
</head>

<body class="theme-blush">

<div class="authentication">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-12">
                <form class="card auth_form">
                    <div class="header">
                        <img class="logo" src="{% static 'assets/images/logo.svg' %}" alt="">
                        <h5>Novo ticket criado</h5>
                        <span>Verifique seu email para mais detalhes</span>
                    </div>
                    <div class="body">
                        <a href="{% url 'login' %}" class="btn btn-primary btn-block waves-effect waves-light">ACESSAR</a>
                        <div class="signin_with mt-3">
                            <a href="javascript:void(0);" class="link">Precisa de ajuda?</a>
                        </div>
                    </div>
                </form>
                <div class="copyright text-center">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>
                    <span><a href="{% url 'dashboard' %}" target="_blank">zDesk</a></span>
                </div>
            </div>
            <div class="col-lg-8 col-sm-12">
                <div class="card">
                    <img src="{% static 'assets/images/maintanance.svg' %}"/>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Jquery Core Js -->
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->
</body>
</html>

templates/helpdesk/create_ticket_step01.html
<!doctype html>
{% load static %}
<html class="no-js " lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Django simple ticketing system">

    <title>:: zDesk :: Você precisa de ajuda com qual equipamento?</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png"> <!-- Favicon-->
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">

    <style type="text/css">
        label {
            cursor: pointer;
            filter: grayscale(100%);
        }

        label:hover {
            filter: grayscale(0);
        }

        input[type="radio"]:checked + label {
            filter: grayscale(0);
        }
    </style>
</head>

<body class="theme-blue">
<section class="content" style="margin: 20px; padding: 20px;">

    <div class="body_scroll">
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2>Você precisa de ajuda com qual <strong>equipamento?</strong></h2>
                        </div>
                        <div class="body">
                            <form action="{% url 'ticket_create_step02' %}" method="post">
                                {% csrf_token %}

                                <div class="row">

                                    {% for queue in queues %}
                                        <div class="col-lg-4 col-md-12">
                                            <div class="form-group d-flex justify-content-around">
                                                <input type="radio" name="maquina" class="sr-only" id="{{ queue.title }}" value="{{ queue.title }}" required>
                                                <label for="{{ queue.title }}">
                                                    <h2 class="align-center m-2">{{ queue.title }}</h2>
                                                    <img src="{{ queue.image.url }}" alt="{{ queue.title }}">
                                                </label>
                                            </div>
                                        </div>
                                    {% endfor %}

                                    <div class="col-12">
                                        <button class="btn btn-primary btn-lg">Próximo</button>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Jquery Core Js -->
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->

</body>
</html>

templates/helpdesk/ticket_add.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'assets/plugins/dropify/css/dropify.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-select/css/bootstrap-select.css' %}"/>
{% endblock extra_css %}

{% block content %}
    <section class="content">
        <div class="body_scroll">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-7 col-md-6 col-sm-12">
                        <h2>Novo Ticket</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'dashboard' %}"><i class="zmdi zmdi-home"></i>zDesk</a>
                            </li>
                            <li class="breadcrumb-item">Tickets</li>
                            <li class="breadcrumb-item active">Novo</li>
                        </ul>
                        <button class="btn btn-primary btn-icon mobile_menu" type="button">
                            <i class="zmdi zmdi-sort-amount-desc"></i></button>
                    </div>
                    <div class="col-lg-5 col-md-6 col-sm-12">

                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row clearfix">

                    {% if form.errors %}
                        {{ form.errors }}
                    {% endif %}

                    <div class="col-lg-8 col-md-12">
                        <div class="card">
                            <div class="header">
                                <h2>Novo<strong> Ticket</strong></h2>
                            </div>
                            <div class="body">
                                <form action="." method="post" id="newTicket" data-questions-url="{% url 'load_questions' %}">
                                    {% csrf_token %}

                                    <div class="row">
                                        <div class="col-md-12 mb-3">
                                            <label for="id_status">Queue:</label>
                                            {{ form.queue }}
                                        </div>
                                        <div class="col-md-12 checkbox-group options">

                                            <div id="questions"></div>


                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <textarea name="outro-problema" id="outro-problema" rows="4" class="form-control no-resize" placeholder="Especifique o problema" style="display: none;"></textarea>
                                            </div>
                                        </div>

                                        <div class="col-md-12 mb-3">
                                            <label for="id_status">Status:</label>
                                            {{ form.status }}
                                        </div>

                                        <div class="col-md-12 mb-3">
                                            <label for="id_priority">Prioridade:</label>
                                            {{ form.priority }}
                                        </div>

                                        <div class="col-md-12 mb-3">
                                            <label for="id_tecnico_pre_diagnostico">Pré diagnostico:</label>
                                            {{ form.tecnico_pre_diagnostico }}
                                        </div>

                                        <div class="col-md-12 mb-3">
                                            <label for="id_tecnico_de_campo">Técnico de campo:</label>
                                            {{ form.tecnico_de_campo }}
                                        </div>


                                        <div class="col-md-12 checkbox-group my-3">
                                            <div class="checkbox">
                                                {{ form.is_customer }}
                                                <label for="id_is_customer">Cliente</label>
                                            </div>
                                        </div>

                                        <div class="col-md-12 mb-3">
                                            <label for="id_customer_code">Cliente:</label>
                                            {{ form.customer_code }}
                                        </div>

                                        <div class="col-md-12 checkbox-group my-3">
                                            <div class="checkbox">
                                                {{ form.need_paper }}
                                                <label for="id_need_paper">Papel</label>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-12">
                                            <div class="form-group">
                                                <label for="id_submitter_name">Cliente:</label>
                                                {{ form.submitter_name }}
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-12">
                                            <div class="form-group">
                                                <label for="id_submitter_company">Empresa:</label>
                                                <input id="id_submitter_company" name="submitter_company" type="text" class="form-control" placeholder="Nome da empresa">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-12">
                                            <div class="input-group masked-input mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="zmdi zmdi-email"></i></span>
                                                </div>
                                                <input id="id_submitter_email" name="submitter_email" type="email" class="form-control email" placeholder="Email cliente" required>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-12">
                                            <div class="input-group masked-input mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="zmdi zmdi-smartphone"></i></span>
                                                </div>
                                                <input id="id_submitter_phone" name="submitter_phone" type="text" class="form-control mobile-phone-number" placeholder="Whats / Celular" required>
                                            </div>
                                        </div>

                                        <div class="col-md-12 align-right">
                                            <button id="save-ticket" class="btn btn-success my-3">Salvar
                                                <i class="zmdi zmdi-save"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12">
                        <div class="card mcard_3">
                            <div class="body">
                                <a href="profile.html">
                                    {% if user.userprofile.avatar %}
                                        <img src="{{ user.userprofile.avatar.url }}" class="rounded-circle shadow " alt="Profile image">
                                    {% else %}
                                        <img src="{% static 'assets/images/profile_av.jpg' %}" class="rounded-circle shadow " alt="Profile image">
                                    {% endif %}
                                </a>
                                <h4 class="m-t-10">{{ user }}</h4>
                                <div class="row">
                                    <div class="col-12">
                                        <ul class="social-links list-unstyled">
                                            <li>
                                                <a title="facebook" href="javascript:void(0);"><i class="zmdi zmdi-facebook"></i></a>
                                            </li>
                                            <li>
                                                <a title="twitter" href="javascript:void(0);"><i class="zmdi zmdi-twitter"></i></a>
                                            </li>
                                            <li>
                                                <a title="instagram" href="javascript:void(0);"><i class="zmdi zmdi-instagram"></i></a>
                                            </li>
                                        </ul>
                                        <p class="text-muted">795 Folsom Ave, Suite 600 San Francisco, CADGE 94107</p>
                                        <small class="text-muted">Email address: </small>
                                        <p>{{ user.email }}</p>
                                        <hr>
                                        <small class="text-muted">Phone: </small>
                                        <p>+ 202-555-0191</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'assets/plugins/jquery-inputmask/jquery.inputmask.bundle.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-notify/bootstrap-notify.js' %}"></script>
    <!-- Bootstrap Notify Plugin Js -->

    <script>
        function showOtherField() {
            const checkBox = document.getElementById("procheckoutros");
            const otherfield = document.getElementById("outro-problema");
            if (checkBox.checked == true) {
                otherfield.style.display = "block";
                otherfield.setAttribute("required", "");
                otherfield.setAttribute("name", "outros problemas");
            } else {
                otherfield.style.display = "none";
                otherfield.removeAttribute("required");
                otherfield.removeAttribute("name");
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $('#id_submitter_phone').inputmask('(99) 9999[9]-9999');
        });
    </script>
    <script>
        $("#id_queue").change(function () {
            let url = $("#newTicket").attr("data-questions-url");   // get the url of the `load_questions` view
            let queueId = $(this).val();                            // get the selected queue ID from the HTML input

            $.ajax({                        // initialize an AJAX request
                url: url,                   // set the url of the request (= localhost:8000/tickets/ajax/load-questions/)
                data: {
                    'queue': queueId        // add the queue id to the GET parameters
                },
                success: function (data) {      // `data` is the return of the `load_questions` view function
                    $("#questions").html(data); // replace the contents of the questions div with the data that came from the server
                }
            });
        });
    </script>
    <script>
        $(function () {
            $('#save-ticket').on('click', function () {
                let isChecked = $('input:checkbox').is(':checked');

                if (isChecked === false) {
                    $.notify({
                        title: '<strong>Atenção!</strong>',
                        message: 'Você precisa selecionar ao menos um item da lista'
                    }, {
                        allow_dismiss: false,
                        type: 'warning'
                    });
                } else {

                }
            });
        });
    </script>
{% endblock %}